// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIihNBPv-JM9oGTxzJs69w-u59xRo7XW4',
    appId: '1:815894335973:web:6c975d973c38496a981f0c',
    messagingSenderId: '815894335973',
    projectId: 'brand-d023c',
    authDomain: 'brand-d023c.firebaseapp.com',
    storageBucket: 'brand-d023c.firebasestorage.app',
    measurementId: 'G-C4E393XC28',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrQgHyDjsde82M5evxuFm5n7_mwcs-Nns',
    appId: '1:815894335973:android:2b659f52f3d9a42f981f0c',
    messagingSenderId: '815894335973',
    projectId: 'brand-d023c',
    storageBucket: 'brand-d023c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAT99WA2hv3dfrPQZi4tiotyk6rDwdUYPo',
    appId: '1:815894335973:ios:d13b499ca9e26811981f0c',
    messagingSenderId: '815894335973',
    projectId: 'brand-d023c',
    storageBucket: 'brand-d023c.firebasestorage.app',
    iosBundleId: 'com.example.brand',
  );
}
